# Generated by Django 3.0.8 on 2020-07-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currentBid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='auctions.Bid'),
        ),
    ]
