# Generated by Django 3.0.8 on 2020-07-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200715_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListing',
            new_name='Auction',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
