# Generated by Django 3.0.8 on 2020-07-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200725_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currentBid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='auctions.Bid'),
        ),
    ]
