# Generated by Django 3.0.8 on 2020-07-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200715_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.Comment'),
        ),
    ]
