# Generated by Django 3.0.8 on 2020-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200716_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
