# Generated by Django 3.0.8 on 2020-07-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auctions', to='auctions.Comment'),
        ),
    ]
