# Generated by Django 3.0.8 on 2020-07-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200716_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='comment',
        ),
    ]
