# Generated by Django 3.0.8 on 2020-07-15 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200715_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.ForeignKey(default=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]), on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.Bid'),
        ),
    ]
