# Generated by Django 3.0.8 on 2020-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
